// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  biography: dynamic(() => import("./Biography")),
  content_index: dynamic(() => import("./ContentIndex")),
  expirience: dynamic(() => import("./Expirience")),
  hero: dynamic(() => import("./Hero")),
  porjects: dynamic(() => import("./Porjects")),
  tech_list: dynamic(() => import("./TechList")),
  text_block: dynamic(() => import("./TextBlock")),
  workpickker: dynamic(() => import("./Workpickker")),
};
